# sudo apt install tmuxinator
name: BASE
root: ~/URC
windows:
  -  R3: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - "#top"
        - htop
        - dmesg -w
        - 
  - SCI:
      root: ~/URC/rosws/src/rover_science/
      layout: tiled
      panes:
        - bash
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
        - '#~/URC/devstuff/components/Panarama/panotools.sh "$(ls ~/URC/*.jpg)"'
  - CAMERAS:
      layout: tiled
      panes:
        - "#rqt_image_view /camera/rgb_fixed/compressed" # Zed Left Camera
        - "#rqt --perspective-file ./devstuff/dan/gui_configs/rqt_all_cameras.perspective" # All Cameras
        - "#roslaunch rover_teleoperation view_zed.launch"
  - RQT:
      layout: tiled
      panes:
        - rosrun rqt_tf_tree rqt_tf_tree
        - rqt_graph
        - "#./rosws/src/rover/src/mapviz_click_to_gps_goal.py"
        - ./rosws/src/rover/src/point_to_marker.py --scale 2
  - RVIZ:
      layout: tiled
      panes:
        - "#roslaunch rover_navigation view_navigation.launch"
        - "#rviz"
        #- "#roslaunch rover_rtabmap_config mapping_rviz.launch"
        #- "#roslaunch rover_robot_localization odom_debug_rviz.launch"
  - MAPVIZ:
      root: ~/URC/devstuff/dan/mapping/
      layout: tiled
      panes:
        - "#roslaunch ./mapviz.launch"
        - sudo docker run -p 8080:8080 -d -t -v ~/mapproxy:/mapproxy danielsnider/mapproxy
  - RTABMAPVIZ:
      root: ~/URC/rosws/src/rover_navigation/
      layout: tiled
      panes:
        - "#roslaunch rover_navigation rtabmapviz.launch"
  - ARM:
      root: ~/URC/rosws/src/rover_arm/
      layout: tiled
      panes:
        - "#roslaunch rover_teleoperation arm_teleoperation.launch dev:=/dev/input/js0"
        - rostopic echo /joy_arm
  - DRIVE:
      root: ~/URC/rosws/src/rover_teleoperation/
      layout: tiled
      panes:
        - "#roslaunch rover_teleoperation drive_teleoperation.launch dev:=/dev/input/js0"
        - rostopic echo /joy
  - WAYPOINT:
      root: ~/URC/rosws/src/rover/src/
      layout: tiled
      panes:
        - "python follow_waypoints.py"
        - "#rostopic pub /path_ready std_msgs/Empty -1"
        - "#rostopic pub -1 /move_base/cancel actionlib_msgs/GoalID -- {}"
  - GO2GPS:
      root: ~/URC/rosws/src/rover/src/
      layout: tiled
      panes:
        - python gps_goal.py --help
        - "#rostopic pub -1 /move_base/cancel actionlib_msgs/GoalID -- {}"
  - OVERLAY:
      root: ~/URC/devstuff/components/ImageOverlay/
      layout: tiled
      panes:
        - "#python ./overlay_scale_and_compass.py"
        - "#rostopic pub /science/scale std_msgs/Float32 3.2"
        - "#rostopic pub /gps/heading std_msgs/Float32 180"
        - "#rqt_image_view /science/overlay/compressed"
        - "#./overlay_scale_and_compass.py  --once --output-file out.jpg --heading 10 --scale 100 --image input.png"
  # - IMU:
  #     root: ~/URC
  #     layout: tiled
  #     panes:
  #       - "#rqt --perspective-file ./devstuff/dan/IMU.perspective"
